function drawAll(){CH=[];
chart('chComp',(s,W,n)=>{const L=16,R=24,max=Math.max(...D.comp.map(c=>c[0]))*1.07,x=v=>L+v/max*(W-L-R),y=92,cw=6.4;
el('line',{x1:L,x2:W-R,y1:y,y2:y,stroke:'var(--axis)','stroke-width':3,'stroke-linecap':'round'},s);
const step=max>24000?10000:max>12000?5000:max>5000?2500:1000;for(let g=0;g<max;g+=step){if(n&&(g/step)%2)continue;el('line',{x1:x(g),x2:x(g),y1:y-5,y2:y+5,stroke:'var(--axis)'},s);el('text',{x:x(g),y:y+22,'text-anchor':'middle'},s).textContent=g===0?'0':br(g/1000,step<1000?1:0)+' mil'}
const used={up:[],dn:[]};let maxRow=0;
[...D.comp].sort((a,b)=>a[0]-b[0]).forEach(([v,t,c,up])=>{const cx=x(v),big=t==='Ontem'||t===D.compBig,side=up<0?'up':'dn',w=Math.max(t.length,fmt(v).length)*cw+8;
 let an='middle',x0=cx-w/2;if(cx+w/2>W){an='end';x0=cx-w}if(cx-w/2<0){an='start';x0=cx}
 let row=0;while(used[side].some(([a,b,r])=>r===row&&x0<b&&x0+w>a))row++;used[side].push([x0,x0+w,row]);maxRow=Math.max(maxRow,row);
 const ly=up<0?y-40-row*30:y+48+row*30;el('line',{x1:cx,x2:cx,y1:up<0?ly+6:y+8,y2:up<0?y-8:ly-14,stroke:'var(--axis)'},s);el('circle',{cx,cy:y,r:big?8:6,fill:c,stroke:'#fff','stroke-width':2},s);
 el('text',{x:cx,y:ly-4,'text-anchor':an,style:big?'fill:var(--crit);font-weight:700':'fill:var(--ink);font-weight:600'},s).textContent=t;el('text',{x:cx,y:ly+10,'text-anchor':an,style:big?'fill:var(--crit)':'fill:var(--ink2)'},s).textContent=fmt(v);hover(el('circle',{cx,cy:y,r:14,fill:'transparent'},s),`<b>${t}</b><br>${fmt(v)}`)});
const upRows=Math.max(0,...used.up.map(u=>u[2])),dnRows=Math.max(0,...used.dn.map(u=>u[2])),top=y-40-upRows*30-16;
s.querySelectorAll('*').forEach(e=>{['y','y1','y2','cy'].forEach(a=>{if(e.hasAttribute(a))e.setAttribute(a,+e.getAttribute(a)-top)})});return y-top+48+dnRows*30+16});
chart('chRev',(s,W,n)=>{const v=D.serie.map(r=>r[1]),mm=D.serie.map(r=>r[2]);const st=Math.max(...v)>20000?10000:5000;const H=n?170:190,L=34,B=22,T=12,max=Math.ceil(Math.max(...v)/st)*st||st,bw=(W-L)/v.length,y=x=>H-B-(x/max)*(H-B-T);
for(let g=0;g<=max;g+=st){el('line',{x1:L,x2:W,y1:y(g),y2:y(g),stroke:'var(--grid)'},s);el('text',{x:L-6,y:y(g)+4,'text-anchor':'end'},s).textContent=g/1000}
v.forEach((x,i)=>{const dt=new Date(D.serie[i][0]+'T12:00:00'),last=i===v.length-1,same=(dt.getDay()+6)%7===D.wd;el('rect',{x:L+i*bw+1,y:y(x),width:bw-2,height:H-B-y(x),rx:3,fill:last?'var(--crit)':same?'var(--s1)':'var(--s1soft)'},s);
 hover(el('rect',{x:L+i*bw,y:T,width:bw,height:H-B-T,fill:'transparent'},s),`<b>${dt.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'})}</b><br>${fmt(x)}`);if(i%(n?7:4)===0||last)el('text',{x:L+i*bw+bw/2,y:H-6,'text-anchor':'middle'},s).textContent=dt.getDate()+'/'+(dt.getMonth()+1)});
const pts=mm.map((m,i)=>[L+i*bw+bw/2,y(m)]);let d='M'+pts[0].join(' ');for(let i=1;i<pts.length;i++){const[p0,p1]=[pts[i-1],pts[i]],cx=(p0[0]+p1[0])/2;d+=` C${cx} ${p0[1]},${cx} ${p1[1]},${p1[0]} ${p1[1]}`}el('path',{d,fill:'none',stroke:'var(--line)','stroke-width':2},s);
let mr=-1e9,mrow=0;D.marcos.forEach(([dd,t])=>{const i=D.serie.findIndex(r=>r[0]===dd);if(i<0)return;const xx=L+i*bw+bw/2,tw=t.length*6.2,end=xx+4+tw>W,x0=end?xx-4-tw:xx+4;mrow=x0<mr+6?mrow+1:0;mr=x0+tw;el('line',{x1:xx,x2:xx,y1:T-2,y2:H-B,stroke:'var(--axis)','stroke-dasharray':'3 3'},s);el('text',{x:end?xx-4:xx+4,y:T+4+mrow*13,'text-anchor':end?'end':'start',style:'fill:var(--ink2);font-weight:600',class:'halo'},s).textContent=t});
el('line',{x1:L,x2:W,y1:H-B,y2:H-B,stroke:'var(--axis)'},s);return H});
chart('chLost',(s,W,n)=>{const max=Math.max(...D.lost.map(l=>l[1]))*1.05;
if(n){const rh=42,x=v=>v/max*(W-90);D.lost.forEach(([nm,v,tr,trc],i)=>{const yy=i*rh;el('text',{x:0,y:yy+13,style:'fill:var(--ink);font-weight:600;font-size:12px'},s).textContent=nm;el('text',{x:W,y:yy+13,'text-anchor':'end'},s).textContent=tr+' a caminho';el('rect',{x:0,y:yy+19,width:Math.max(3,x(v)),height:13,rx:4,fill:'var(--crit)'},s);el('text',{x:x(v)+6,y:yy+30,style:'fill:var(--ink2);font-weight:600'},s).textContent=fmt(v)+'/dia';hover(el('rect',{x:0,y:yy,width:W,height:rh,fill:'transparent'},s),`<b>${nm}</b><br>${fmt(v)}/dia · ${tr} un. em trânsito cobrem ${br(trc,0)} dias`)});return D.lost.length*rh}
const L=Math.min(200,W*.28),rh=32,x=v=>L+v/max*(W-L-190);
D.lost.forEach(([nm,v,tr,trc],i)=>{const yy=i*rh+2;el('text',{x:L-10,y:yy+17,'text-anchor':'end',style:'fill:var(--ink);font-size:12px'},s).textContent=nm;el('rect',{x:L,y:yy+5,width:x(v)-L,height:16,rx:4,fill:'var(--crit)'},s);el('text',{x:x(v)+8,y:yy+17,style:'fill:var(--ink2)'},s).textContent=fmt(v)+'/dia  ('+tr+' a caminho)';hover(el('rect',{x:0,y:yy,width:W,height:rh,fill:'transparent'},s),`<b>${nm}</b><br>${fmt(v)}/dia · ${tr} un. em trânsito cobrem ${br(trc,0)} dias`)});return D.lost.length*rh+8});
chart('chCtr',(s,W,n)=>{const v=D.ctr.map(r=>r[2]?r[1]/r[2]*100:0),avg=D.ctr.reduce((a,r)=>a+r[1],0)/Math.max(1,D.ctr.reduce((a,r)=>a+r[2],0))*100,top=Math.max(1,Math.ceil(Math.max(...v)*2)/2);const H=130,L=34,B=20,T=8,x=i=>L+i*(W-L-10)/(v.length-1),y=c=>H-B-c/top*(H-B-T);
[0,top/2,top].forEach(g=>{el('line',{x1:L,x2:W,y1:y(g),y2:y(g),stroke:'var(--grid)'},s);el('text',{x:L-6,y:y(g)+4,'text-anchor':'end'},s).textContent=br(g,1)+'%'});el('line',{x1:L,x2:W,y1:y(avg),y2:y(avg),stroke:'var(--ink2)','stroke-dasharray':'4 4'},s);
el('polyline',{points:v.map((c,i)=>x(i)+','+y(c)).join(' '),fill:'none',stroke:'var(--s1)','stroke-width':2},s);
v.forEach((c,i)=>{const last=i===v.length-1;el('circle',{cx:x(i),cy:y(c),r:last?5:3,fill:last?'var(--crit)':'var(--s1)',stroke:'#fff','stroke-width':2},s);hover(el('rect',{x:x(i)-12,y:T,width:24,height:H-B-T,fill:'transparent'},s),`<b>${D.ctr[i][0]}</b><br>CTR ${br(c,2)}%`);const stp=W<380?4:3;if((i%stp===0&&i<v.length-stp+1)||last)el('text',{x:x(i),y:H-4,'text-anchor':last?'end':'middle'},s).textContent=D.ctr[i][0]});return H});
chart('chProj',(s,W,n)=>{const [a,b,c,m]=D.proj;const hi=Math.max(b,c,m),min=Math.max(0,Math.floor(a/20)*20-10),max=Math.ceil(hi/20)*20+10,x=v=>12+(v-min)/(max-min)*(W-24);
el('rect',{x:12,y:26,width:W-24,height:10,rx:5,fill:'var(--grid)'},s);el('rect',{x:x(a),y:26,width:Math.max(0,x(b)-x(a)),height:10,fill:'var(--s1)'},s);if(c>b+0.5)el('rect',{x:x(b),y:26,width:x(c)-x(b),height:10,fill:'var(--critbg)',stroke:'var(--crit)','stroke-dasharray':'3 2'},s);
if(m){el('line',{x1:x(m),x2:x(m),y1:14,y2:44,stroke:'var(--good)','stroke-width':2.5},s);el('text',{x:x(m),y:10,'text-anchor':'middle',style:'fill:var(--good);font-weight:700'},s).textContent='meta '+br(m,0)}
const lb=[[a,(D.projHoje||'hoje')+' '+br(a,1)],[b,br(b,0)+' previsto']];if(c>b+0.5)lb.push([c,br(c,0)+' com estoque']);lb.forEach(([v,t],i)=>{const xv=x(v);el('line',{x1:xv,x2:xv,y1:20,y2:42,stroke:'var(--ink2)','stroke-width':1.5},s);el('text',{x:xv,y:58+(i===2?14:0),'text-anchor':xv<50?'start':xv>W-50?'end':'middle'},s).textContent=t});return c>b+0.5?86:70});
chart('chCov',(s,W,n)=>{const rows=D.ws,max=30,L=n?0:Math.min(180,W*.26),rh=n?38:28,T=8,x=v=>L+v/max*(W-L-(n?50:60)),Hb=T+rh*rows.length;
el('rect',{x:L,y:T-4,width:x(D.lt)-L,height:Hb-T+4,fill:'var(--critbg)',opacity:.55},s);el('rect',{x:x(D.lt),y:T-4,width:W-x(D.lt),height:Hb-T+4,fill:'var(--goodbg)',opacity:.5},s);
[0,7,14,21,28].forEach(g=>{el('line',{x1:x(g),x2:x(g),y1:T-4,y2:Hb,stroke:'#fff'},s);el('text',{x:x(g),y:Hb+16,'text-anchor':g===0&&n?'start':'middle'},s).textContent=g+(n?'d':' dias')});
rows.forEach(([nm,e,cov],i)=>{const yy=T+i*rh,w=Math.max(x(Math.min(cov,max))-L,3),by=n?yy+18:yy+5;if(n)el('text',{x:4,y:yy+13,style:'fill:var(--ink);font-weight:600;font-size:12px',class:'halo'},s).textContent=nm;else el('text',{x:L-10,y:yy+17,'text-anchor':'end',style:'fill:var(--ink);font-weight:500;font-size:12px'},s).textContent=nm;el('rect',{x:L,y:by,width:w,height:n?13:16,rx:4,fill:cov<D.lt?'var(--crit)':'var(--good)'},s);el('text',{x:L+w+6,y:by+(n?11:12),style:'fill:var(--ink);font-weight:600',class:'halo'},s).textContent=(cov>max?'+'+max:br(cov,1))+(n?'d':' dias');hover(el('rect',{x:0,y:yy,width:W,height:rh,fill:'transparent'},s),`<b>${nm}</b><br>${e} un. · ${br(cov,1)} dias`)});
const lx=x(D.lt);el('line',{x1:lx,x2:lx,y1:T-8,y2:Hb,stroke:'var(--crit)','stroke-width':2},s);el('text',{x:lx-6,y:Hb+32,'text-anchor':'end',style:'fill:var(--crit);font-weight:600'},s).textContent=n?'◀ não chega':'◀ não chega a tempo';el('text',{x:lx+6,y:Hb+32,style:'fill:var(--good);font-weight:600'},s).textContent=n?'chega ▶':'chega a tempo ▶';return Hb+40});
(()=>{const w=$('wx');if(!w)return;const ic={sun:'<svg viewBox="0 0 24 24" fill="none" stroke="#e9a400" stroke-width="2"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>',cloud:'<svg viewBox="0 0 24 24" fill="none" stroke="#8a919c" stroke-width="2"><path d="M7 18h10a4 4 0 0 0 .5-8 6 6 0 0 0-11.3 1.5A3.3 3.3 0 0 0 7 18z"/></svg>',rain:'<svg viewBox="0 0 24 24" fill="none" stroke="#2a78d6" stroke-width="2"><path d="M7 15h10a4 4 0 0 0 .5-8 6 6 0 0 0-11.3 1.5A3.3 3.3 0 0 0 7 15z"/><path d="M8 18l-1 3M12 18l-1 3M16 18l-1 3"/></svg>',storm:'<svg viewBox="0 0 24 24" fill="none" stroke="#d03b3b" stroke-width="2"><path d="M7 14h10a4 4 0 0 0 .5-8 6 6 0 0 0-11.3 1.5A3.3 3.3 0 0 0 7 14z"/><path d="M13 14l-2 4h3l-2 4"/></svg>'};
const tp=D.wxt||'chuva';D.wx.forEach(([d,p,k,t,al])=>{const tn=parseInt(t),hot=tp==='chuva'?p>=50:tp==='frio'?tn<=12:tn>=32;w.insertAdjacentHTML('beforeend',`<div class="wxd${hot?' rain':''}${al?' al':''}"><div class="dy">${d}</div>${ic[k]||ic.cloud}<div class="pp">${tp==='chuva'?p+'%':t}</div><div class="mm">${tp==='chuva'?'chuva · '+t:tp==='frio'?'mínima · chuva '+p+'%':'máxima · chuva '+p+'%'}</div>${al?'<div class="altag">INMET</div>':''}</div>`)});})();
chart('chCal',(s,W,n)=>{const L=12,R=12,d0=new Date(D.hoje+'T12:00:00'),days=72,x=d=>L+Math.max(0,Math.min(days,(d-d0)/864e5))/days*(W-L-R),yb=66,anc=xx=>xx>W-70?'end':xx<70?'start':'middle';
if(D.estacao){const e0=new Date(D.estacao.inicio+'T12:00:00'),xe=x(e0);el('rect',{x:xe,y:yb-9,width:W-R-xe,height:6,rx:3,fill:'var(--line)',opacity:.35},s);el('text',{x:W-R,y:yb-22,'text-anchor':'end',style:'fill:var(--ink2)'},s).textContent=D.estacao.texto}
el('line',{x1:L,x2:W-R,y1:yb,y2:yb,stroke:'var(--axis)','stroke-width':3,'stroke-linecap':'round'},s);
for(let i=0;i<=days;i+=7){const d=new Date(d0);d.setDate(d0.getDate()+i);el('line',{x1:x(d),x2:x(d),y1:yb-4,y2:yb+4,stroke:'var(--axis)'},s);if(i%(n?21:14)===0&&i>0)el('text',{x:x(d),y:yb+18,'text-anchor':anc(x(d))},s).textContent=d.getDate()+'/'+(d.getMonth()+1)}
el('circle',{cx:x(d0),cy:yb,r:5,fill:'var(--ink)'},s);el('text',{x:x(d0),y:yb+18,'text-anchor':'start',style:'fill:var(--ink);font-weight:600'},s).textContent='hoje';
let row=0;D.ev.forEach(([ds,t,bs,c])=>{const d=new Date(ds+'T12:00:00');if((d-d0)/864e5>days)return;const xe=x(d);el('circle',{cx:xe,cy:yb,r:7,fill:c,stroke:'#fff','stroke-width':2},s);el('text',{x:xe,y:yb+34,'text-anchor':anc(xe),style:'fill:var(--ink);font-weight:700'},s).textContent=t;
 if(bs){const b=new Date(bs+'T12:00:00'),past=b<=d0,xb=past?x(d0):x(b),ty=14+(row++%2)*14;if(!past)el('path',{d:`M${xb} ${yb-6} l-5 -9 h10 z`,fill:c},s);el('line',{x1:xb,x2:xb,y1:ty+4,y2:yb-(past?6:15),stroke:past?'var(--crit)':'var(--axis)','stroke-dasharray':'2 2'},s);el('text',{x:xb,y:ty,'text-anchor':past?'start':anc(xb),style:past?'fill:var(--crit);font-weight:700':'fill:var(--ink2)'},s).textContent=past?'⚠ comprar hoje · '+t:'comprar até '+b.getDate()+'/'+(b.getMonth()+1)}
 hover(el('circle',{cx:xe,cy:yb,r:14,fill:'transparent'},s),`<b>${t}</b> ${d.getDate()}/${d.getMonth()+1}`)});return yb+44});

}
